---
# Jenkins Plugins List
# Each item should be the technical name of the plugin

plugins:
  - git
  - docker
  - docker-compose
  - kubernetes
  - pipeline
  - blueocean
  - workflow-aggregator
  - configuration-as-code
  - docker-plugin
  - docker-java-api
