---
# Role metadata

galaxy_info:
  author: Rafael Guzman
  description: Jenkins initial setup and deployment
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - jenkins
    - docker
    - ci
    - cd
    - setup

dependencies: []
